// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpprexurqzixebfuneni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwcHJleHVycXppeGViZnVuZW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MjAxNTUsImV4cCI6MjA1NDI5NjE1NX0.RWP-nazli-L_31r4_uqGIHUiyg9RdxM02EfWz0444Oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);